# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 13:54
from __future__ import unicode_literals

import core.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170922_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MY_PROFILE', 'MyProfile')], default=core.enums.ModuleEnum('MyProfile'), max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('MEMBER', 'Member')], default='MEMBER', max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='core.Module'),
        ),
    ]
